(ns jirgee.screens.profile-view
  (:require
   ["package:flutter/material.dart" :as m]
   [cljd.flutter.alpha2 :as f]
   [jirgee.widgets.user-profile :as user-profile]
   [jirgee.states.global :as gs]))

(defn ^m/Widget screen [ctx]
  (let [userinfo (:user-info @gs/state)]
    (f/widget
     (m/Scaffold
      .appBar  nil)
     .body
     (m/SafeArea
      .child
      (user-profile/view userinfo)))))