(ns jirgee.services.file
  (:require
   ["package:path_provider/path_provider.dart" :as path-provider]))

;;
;; String.fromCharCode (72)


(defn export-to-file []
  (let [directory (await (path-provider/getExternalStorageDirectory))
        directory (if (empty? directory)
                    (path-provider/getApplicationDocumentsDirectory)
                    directory)
        file-name (-> (.now DateTime) .toString (.substring 0 19))]))