(ns jirgee.main
  (:require
   ["package:flutter/material.dart" :as m]
   [cljd.flutter :as f]))

(defn main []
  (m.WidgetsFlutterBinding/ensureInitialized)

  (f/run
   (m/MaterialApp
    .title "Jirgee"
    .theme (m/ThemeData
            .fontFamily "OyunQaganTig"
            .primaryColor m/Colorsblue
            .darkness m/Brightness.dark)
    .body (m/Center .child (m/Text "Hello, World!"))
    .debugShowCheckedModeBanner false)))
