(ns jirgee.common.response
  (:require
   ["dart:convert" :as convert]
   ["package:http/http.dart" :as http]
   [jirgee.common.utils :as utils]))

(defn response-message [ctx ^http/Response response success-fn]
  (let [response-body (convert/jsonDecode (.-body response))]
    (if (not= 200 (.-statusCode response))
      (utils/show-toast ctx (get-in response-body ["data" "message"]))
      (success-fn response-body))))